export const products = [
  {
    id: 'parna-balconette',
    name: 'Parna Balconette',
    price: 5799,
    image: 'https://images.unsplash.com/photo-1617331721458-bd3bd3f9c7e8?w=500&h=600&fit=crop',
    description: 'Elegant balconette bra with premium lace detailing. Perfect blend of comfort and style.',
    category: 'bras',
  },
  {
    id: 'parna-bodysuit',
    name: 'Parna Bodysuit',
    price: 7199,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085aae?w=500&h=600&fit=crop',
    description: 'Sophisticated bodysuit crafted for a flawless silhouette. Premium fabric, all-day comfort.',
    category: 'bodysuits',
  },
  {
    id: 'parna-bralette',
    name: 'Parna Bralette',
    price: 5599,
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&h=600&fit=crop',
    description: 'Delicate bralette with intricate detailing. Lightweight support for everyday elegance.',
    category: 'bras',
  },
  {
    id: 'parna-cheeky',
    name: 'Parna Cheeky',
    price: 2099,
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500&h=600&fit=crop',
    description: 'Cheeky brief with premium cotton blend. Comfort meets subtle sophistication.',
    category: 'bottoms',
  },
  {
    id: 'parna-balconette-blush',
    name: 'Parna Balconette - Blush',
    price: 5799,
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=500&h=600&fit=crop',
    description: 'Blush variant of the signature Parna Balconette. Same elegance, softer tone.',
    category: 'bras',
  },
  {
    id: 'parna-bralette-ivory',
    name: 'Parna Bralette - Ivory',
    price: 5599,
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&h=600&fit=crop',
    description: 'Ivory Parna Bralette. Timeless design for the modern wardrobe.',
    category: 'bras',
  },
  {
    id: 'parna-lounge-set',
    name: 'Parna Lounge Set',
    price: 8499,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&h=600&fit=crop',
    description: 'The complete Parna Lounge Set — matching top and bottom for effortless comfort at home.',
    category: 'loungewear',
  },
  {
    id: 'parna-sleep-set',
    name: 'Parna Sleep Set',
    price: 4999,
    image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=500&h=600&fit=crop',
    description: 'Silky sleep set with delicate button-up top and matching shorts. Soft as a whisper.',
    category: 'sleepwear',
  },
  {
    id: 'parna-high-waist',
    name: 'Parna High-Waist Brief',
    price: 2799,
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=500&h=600&fit=crop',
    description: 'Flattering high-waist brief with tummy control. Designed for confidence from day to night.',
    category: 'bottoms',
  },
  {
    id: 'parna-lace-bodysuit',
    name: 'Parna Lace Bodysuit',
    price: 7999,
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&h=600&fit=crop',
    description: 'Premium lace bodysuit with sculpting panels. The ultimate fusion of elegance and function.',
    category: 'bodysuits',
  },
  {
    id: 'parna-sports-bra',
    name: 'Parna Sports Bra',
    price: 4499,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085aae?w=500&h=600&fit=crop',
    description: 'Supportive sports bra with breathable mesh panels. Move freely in style.',
    category: 'bras',
  },
  {
    id: 'parna-midnight-set',
    name: 'Parna Midnight Set',
    price: 8999,
    image: 'https://images.unsplash.com/photo-1617331721458-bd3bd3f9c7e8?w=500&h=600&fit=crop',
    description: 'Deep navy loungewear set with contrast stitching. For those who love the night.',
    category: 'loungewear',
  },
];
