export const products = [
  {
    id: 'parna-balconette',
    name: 'Parna Balconette',
    price: 5799,
    image: 'https://byolakh.com/cdn/shop/files/00_ParnaBalconette.jpg?v=1771694387&width=500',
    description: 'Elegant balconette bra with premium lace detailing. Perfect blend of comfort and style.',
    category: 'bras',
  },
  {
    id: 'parna-bodysuit',
    name: 'Parna Bodysuit',
    price: 7199,
    image: 'https://byolakh.com/cdn/shop/files/00_ParnaBodysuit.jpg?v=1771698424&width=500',
    description: 'Sophisticated bodysuit crafted for a flawless silhouette. Premium fabric, all-day comfort.',
    category: 'bodysuits',
  },
  {
    id: 'parna-bralette',
    name: 'Parna Bralette',
    price: 5599,
    image: 'https://byolakh.com/cdn/shop/files/00_ParnaBralette.jpg?v=1771695794&width=500',
    description: 'Delicate bralette with intricate detailing. Lightweight support for everyday elegance.',
    category: 'bras',
  },
  {
    id: 'parna-cheeky',
    name: 'Parna Cheeky',
    price: 2099,
    image: 'https://byolakh.com/cdn/shop/files/00_ParnaCheeky.jpg?v=1771697765&width=500',
    description: 'Cheeky brief with premium cotton blend. Comfort meets subtle sophistication.',
    category: 'bottoms',
  },
  {
    id: 'parna-balconette-2',
    name: 'Parna Balconette - Blush',
    price: 5799,
    image: 'https://byolakh.com/cdn/shop/files/01_ParnaBalconette.jpg?v=1771694386&width=500',
    description: 'Blush variant of the signature Parna Balconette. Same elegance, softer tone.',
    category: 'bras',
  },
  {
    id: 'parna-bralette-2',
    name: 'Parna Bralette - Ivory',
    price: 5599,
    image: 'https://byolakh.com/cdn/shop/files/01_ParnaBralette.jpg?v=1771695794&width=500',
    description: 'Ivory Parna Bralette. Timeless design for the modern wardrobe.',
    category: 'bras',
  },
];
